"C:\Program Files (x86)\JetBrains\WebStorm 7.0.3\jre\jre\bin\java" - cp
"C:\Program Files (x86)\JetBrains\WebStorm 7.0.3\plugins\JsTestDriver\lib\JsTestDriver-plugin-rt.jar;C:\Program Files (x86)\JetBrains\WebStorm 7.0.3\plugins\JsTestDriver\lib\JsTestDriver-1.3.5-patched.jar;C:\Program Files (x86)\JetBrains\WebStorm 7.0.3\lib\guava-14.0.1.jar;C:\Program Files (x86)\JetBrains\WebStorm 7.0.3\lib\gson-2.2.3.jar"
com.google.jstestdriver.idea.TestRunner--
server_url = http
://127.0.0.1:9876 --config_files=C:/Users/youth/projects/runtime-test-frame/test/js-test-driver.jstd
Testing
started
at
4
:
34
PM...

    Error
:
Expected
{
    id : 0, env
:
    {
        currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
            <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                <circular reference: Object> ], suites_ : [  ], specs_ : [
                    <circular reference: Object> ] } ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                        <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                            <circular reference: Object> ], suites_ : [  ], specs_ : [
                                <circular reference: Object> ] } ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, suite : { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [
                                    <circular reference: Object> ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, ensured : [ false ], blocks : [
                                        <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [
                                            <circular reference: Object> ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, before_ : [  ], after_ : [  ], children_ : [
                                                <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                    <circular reference: Object> ] }, description : 'test jasmine', queue : { env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                        <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                            <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                <circular reference: Object> ] } ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                    <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                        <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                            <circular reference: Object> ] } ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, ensured : [ false ], blocks : [ { env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                                <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                                    <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                        <circular reference: Object> ] } ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                                            <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                                                <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                                    <circular reference: Object> ] } ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, func : Function, spec :
                                                                                                        <circular reference: Object> } ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, afterCallbacks : [  ], spies_ : [  ], results_ : { totalCount : 0, passedCount : 0, failedCount : 0, skipped : false, items_ : [  ], description : 'test jasmine' }, matchersClass : null } to equal null.
                                                                                                        Error: Expected { id : 0, env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                                                            <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                                                                <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                                                    <circular reference: Object> ] } ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                                                                        <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                                                                            <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                                                                <circular reference: Object> ] } ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, suite : { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [
                                                                                                                                    <circular reference: Object> ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, ensured : [ false ], blocks : [
                                                                                                                                        <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [
                                                                                                                                            <circular reference: Object> ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, before_ : [  ], after_ : [  ], children_ : [
                                                                                                                                                <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                                                                                    <circular reference: Object> ] }, description : 'test jasmine', queue : { env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                                                                                                        <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                                                                                                            <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                                                                                                <circular reference: Object> ] } ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                                                                                                                    <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                                                                                                                        <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                                                                                                            <circular reference: Object> ] } ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, ensured : [ false ], blocks : [ { env : { currentSpec : <circular reference: Object>, currentSuite : null, currentRunner_ : { env : <circular reference: Object>, queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                                                                                                                                <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                                                                                                                                    <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                                                                                                                        <circular reference: Object> ] } ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, before_ : [  ], after_ : [  ], suites_ : [ { id : 0, description : 'design for trustworthy software - tools, techniques, and methodology of developing robuse software', queue : { env : <circular reference: Object>, ensured : [ false ], blocks : [ <circular reference: Object> ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, parentSuite : null, env :
                                                                                                                                                                                            <circular reference: Object>, before_ : [  ], after_ : [  ], children_ : [
                                                                                                                                                                                                <circular reference: Object> ], suites_ : [  ], specs_ : [
                                                                                                                                                                                                    <circular reference: Object> ] } ] }, reporter : { onTestDone : Function, onComplete : Function, specLog : [  ], start : 1388651680240 }, updateInterval : 250, defaultTimeoutInterval : 5000, lastUpdate : 0, specFilter : Function, nextSpecId_ : 1, nextSuiteId_ : 1, equalityTesters_ : [  ], matchersClass : Function }, func : Function, spec :
                                                                                                                                                                                                        <circular reference: Object> } ], running : true, index : 0, offset : 0, abort : false, onComplete : Function }, afterCallbacks : [  ], spies_ : [  ], results_ : { totalCount : 0, passedCount : 0, failedCount : 0, skipped : false, items_ : [  ], description : 'test jasmine' }, matchersClass : null } to equal null.
                                                                                                                                                                                                        at null.
                                                                                                                                                                                                            <anonymous> (http://127.0.0.1:9876/test/js-test-driver/books/design-trustworthy-software.js:5:27)



                                                                                                                                                                                                            Process finished with exit code 0
