// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('', function() {
    return it('', function() {
      var reg, url, urlNew, urls;
      url = 'http://xenodesystems.blogspot.com/2013/07/actualizarmigrar-ruby-20-y-rails-4-sin.html';
      urls = ['http://xenodesystems.blogspot.mx/2013/07/actualizarmigrar-ruby-20-y-rails-4-sin.html', 'http://xenodesystems.blogspot.it/2013/07/actualizarmigrar-ruby-20-y-rails-4-sin.html', 'http://xenodesystems.blogspot.fr/2013/07/actualizarmigrar-ruby-20-y-rails-4-sin.html', 'http://xenodesystems.blogspot.com.au/2013/07/actualizarmigrar-ruby-20-y-rails-4-sin.html'];
      reg = /(?=blogspot)(\.[a-zA-Z]+)+/;
      urlNew = urls[1].replace(reg, '.com');
      return expect(urlNew).toEqual(url);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=temp.map
*/
