// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var arr1, arr2, arr5, multiLinesStr, numStr, reg3, reg4, reg6, str6, str6_1, str6_2;

  numStr = 'a1b2c3d4e|55';

  arr1 = numStr.match(/\d+/g);

  multiLinesStr = "first line\n\nsecond line\r\n\n\r\n\n\nthird line\r\n	a";

  arr2 = multiLinesStr.match(/.+/g);

  reg3 = new RegExp('\\d+', 'g');

  reg4 = /\d+/g;

  arr5 = numStr.split(/3|4/);

  str6 = 'aabb';

  reg6 = /^a+b+$/;

  str6_1 = str6.match(/a+/);

  str6_2 = str6.match(/b+/);

  test("qunit test", function() {
    return equal([], [], 'equal in qunit is contents equal test');
  });

  test('reqular expression', function() {
    equal(arr1, [1, 2, 3, 4, 55]);
    equal(arr2, ['first line', 'second line', 'third line', '	a']);
    ok(reg3.global === reg4.global && reg3.source === reg4.source, 'js can create the instance of RegExp object by two ways');
    equal(arr5, ['a1b2c', 'd', 'e|55']);
    ok(reg6.exec(str6));
    equal(str6_1, ['aa']);
    equal(str6_2, ['bb']);
    return ok(str6_1[0].length === str6_2[0].length);
  });

}).call(this);

/*
//@ sourceMappingURL=test-qunit.map
*/
